#
# Copyright (c) 2026, Chloe M.
# Provided under the BSD-3 clause.
#
# Description: Kernel-side build script
# Author:      Chloe M.
#

include mk/stmk.mk

.PHONY: all
all: stoskrnl

.PHONY: stoskrnl
stoskrnl:
	cd stoskrnl/; $(MAKE) $(PASSDOWN_ARGS)
