timeout: 16
interface_branding_color: 7

interface_branding: -- Yiff! --
wallpaper: boot():/boot/wallpaper.jpg
wallpaper_style: tiled

editor_enabled: no
interface_help_hidden: yes
randomize_hhdm_base: yes

/SystemPaw DR
    protocol: limine
    kernel_path: boot():/boot/stoskrnl.sys
    module_path: boot():/boot/pbi.hole
    cmdline: bootcons=false

/SystemPaw DR (bootcons)
    protocol: limine
    kernel_path: boot():/boot/stoskrnl.sys
    module_path: boot():/boot/pbi.hole
    cmdline: bootcons=true
