#
# Copyright (c) 2026, Chloe M.
# Provided under the BSD-3 clause.
#
# Description: Support package build script
# Author:      Chloe M.
#

include ../stos/mk/stmk.mk

.PHONY: all
all:
	cd lib/strlib/; $(MAKE) $(PASSDOWN_ARGS)
